coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: auto
        threshold: 0%
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
flag_management:
  default_rules:
    carryforward: true
    paths:
      - src/
ignore:
  - "**/*.test.ts"
  - "**/testdata/**"
  - "**/node_modules/**"
